# Site settings
title: Rezepte
description: "Eine Sammlung von Rezepten"
baseurl: /rezepte
url: "http://tehlers.github.io/rezepte"

exclude: ["bin", "README.md", "Gemfile", "Gemfile.lock"]

# Build settings
markdown: kramdown
permalink: pretty

defaults:
    -
        scope:
            path: ""
            type: "posts"
        values:
            layout: "recipe"

asciidoctor:
    attributes:
        - hardbreaks!
