# Site settings
title: Rezepte
description: "Eine Sammlung von Rezepten"
baseurl: ""
url: "http://tehlers.github.io/rezepte"

exclude: ["bin", "README.md", "Gemfile", "Gemfile.lock"]

# Build settings
markdown: kramdown
permalink: pretty
